## Imports

In [1]:
import pandas as pd

In [2]:
import pandas as pd

# Read only the first 5 rows of the file
df = pd.read_csv('Taxi_Trips_cleaned.csv', nrows=5)
display(df)
print(df.columns)

,Trip Start Timestamp,Trip End Timestamp,Trip Seconds,Trip Miles,Fare,Tips,Tolls,Extras,Trip Total,Payment Type,Company,Pickup Centroid Latitude,Pickup Centroid Longitude,Dropoff Centroid Latitude,Dropoff Centroid Longitude
0,06/29/2019 11:00:00 PM,06/29/2019 11:15:00 PM,307.0,0.40,4.75,0.0,0.0,1.0,5.75,Cash,Chicago Taxicab,41.892073,-87.628874,41.892042,-87.631864
1,03/31/2023 07:45:00 AM,03/31/2023 08:30:00 AM,2161.0,8.98,30.00,0.0,0.0,1.0,31.00,Prcard,Flash Cab,41.761578,-87.572782,41.660136,-87.602848
2,09/14/2020 03:15:00 PM,09/14/2020 03:30:00 PM,1368.0,2.87,13.75,0.0,0.0,0.0,13.75,Prcard,Flash Cab,41.761578,-87.572782,41.761578,-87.572782
3,09/26/2020 12:45:00 AM,09/26/2020 01:00:00 AM,780.0,4.70,15.00,0.0,0.0,0.0,15.00,Cash,Top Cab Affiliation,41.899602,-87.633308,41.944227,-87.655998
4,08/21/2022 07:45:00 PM,08/21/2022 08:15:00 PM,2004.0,15.45,39.50,9.0,0.0,5.0,54.00,Mobile,Globe Taxi,NaN,NaN,NaN,NaN

Index(['Trip Start Timestamp', 'Trip End Timestamp', 'Trip Seconds',
       'Trip Miles', 'Fare', 'Tips', 'Tolls', 'Extras', 'Trip Total',
       'Payment Type', 'Company', 'Pickup Centroid Latitude',
       'Pickup Centroid Longitude', 'Dropoff Centroid Latitude',
       'Dropoff Centroid Longitude'],
      dtype='object')

In [3]:
df = pd.read_csv('Taxi_Trips_cleaned.csv')
display(df)
print(df.columns)

,Trip Start Timestamp,Trip End Timestamp,Trip Seconds,Trip Miles,Fare,Tips,Tolls,Extras,Trip Total,Payment Type,Company,Pickup Centroid Latitude,Pickup Centroid Longitude,Dropoff Centroid Latitude,Dropoff Centroid Longitude
0,06/29/2019 11:00:00 PM,06/29/2019 11:15:00 PM,307.0,0.40,4.75,0.00,0.0,1.0,5.75,Cash,Chicago Taxicab,41.892073,-87.628874,41.892042,-87.631864
1,03/31/2023 07:45:00 AM,03/31/2023 08:30:00 AM,2161.0,8.98,30.00,0.00,0.0,1.0,31.00,Prcard,Flash Cab,41.761578,-87.572782,41.660136,-87.602848
2,09/14/2020 03:15:00 PM,09/14/2020 03:30:00 PM,1368.0,2.87,13.75,0.00,0.0,0.0,13.75,Prcard,Flash Cab,41.761578,-87.572782,41.761578,-87.572782
3,09/26/2020 12:45:00 AM,09/26/2020 01:00:00 AM,780.0,4.70,15.00,0.00,0.0,0.0,15.00,Cash,Top Cab Affiliation,41.899602,-87.633308,41.944227,-87.655998
4,08/21/2022 07:45:00 PM,08/21/2022 08:15:00 PM,2004.0,15.45,39.50,9.00,0.0,5.0,54.00,Mobile,Globe Taxi,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14705769,01/07/2015 06:30:00 PM,01/07/2015 06:30:00 PM,0.0,0.00,7.85,2.00,0.0,0.0,9.85,Credit Card,Suburban Dispatch LLC,NaN,NaN,NaN,NaN
14705770,07/31/2015 08:00:00 PM,07/31/2015 08:00:00 PM,0.0,0.00,7.75,1.55,0.0,0.0,9.30,Credit Card,Chicago Elite Cab Corp. (Chicago Carriag,NaN,NaN,NaN,NaN
14705771,08/13/2015 10:15:00 AM,08/13/2015 10:15:00 AM,0.0,0.00,40.05,8.01,0.0,0.0,48.06,Credit Card,Suburban Dispatch LLC,NaN,NaN,NaN,NaN
14705772,09/18/2019 07:45:00 PM,09/18/2019 07:45:00 PM,0.0,0.00,3.50,0.00,0.0,0.0,3.50,Cash,Taxi Affiliation Services,41.884987,-87.620993,41.884987,-87.620993
14705773,07/28/2015 09:45:00 PM,07/28/2015 10:15:00 PM,1140.0,0.00,17.65,0.00,0.0,0.0,17.65,Cash,Blue Ribbon Taxi Association Inc.,NaN,NaN,NaN,NaN

Index(['Trip Start Timestamp', 'Trip End Timestamp', 'Trip Seconds',
       'Trip Miles', 'Fare', 'Tips', 'Tolls', 'Extras', 'Trip Total',
       'Payment Type', 'Company', 'Pickup Centroid Latitude',
       'Pickup Centroid Longitude', 'Dropoff Centroid Latitude',
       'Dropoff Centroid Longitude'],
      dtype='object')